name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: ButcherPeteFOSE.sln

permissions: write-all

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Build Debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Generate Timestamp
      run: |
        timestamp=$(date +"%Y%m%d%H%M%S")
        echo "artifact_timestamp=$timestamp" >> $GITHUB_ENV
      shell: bash

    - name: Publish Release
      uses: actions/upload-artifact@v6
      with:
        name: ButcherPeteFOSE-Release-${{ env.artifact_timestamp }}
        path: |
          Release\ButcherPete.dll

    - name: Publish Debug
      uses: actions/upload-artifact@v6
      with:
        name: ButcherPeteFOSE-Debug-${{ env.artifact_timestamp }}
        path: |
          Debug\ButcherPete.dll

    - name: Delete Old Continuous Release
      id: delete_old_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete continuous --yes --cleanup-tag
      shell: bash

    - name: Create Continuous Release
      id: create_continuous_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: continuous
        name: "Continuous release"
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        generateReleaseNotes: true
        artifacts: ButcherPeteFOSE-Release-${{ env.artifact_timestamp }}.zip,ButcherPeteFOSE-Debug-${{ env.artifact_timestamp }}.zip
        body: |
          Continuous release generated from the latest push to development branch.

